### PR TITLE
fix paginated requests

### LINKED ISSUE #60: The tool only displays the first 100 files of a PR in the treeview

### LINKED ISSUE #61: Only the first 100 files get the file patch
The pagination for REST queries is not implemented, thus the tool only receives the file patch for the first 100 files of the PR

### PR DESCRIPTION
**Pull request by TheEmidee**
- **Fixed issue when generating a GraphQL query with an After cursor**
- **Implemented pagination for the REST queries and updated GetPullRequestInfos to fetch all the file patches**
- **Created helper function to know if a file name points to a uasset or umap**
- **Don't store file patches for uasset files**
- **Use IsUAsset in SGitHubToolsPRFilesChanged::GetItemRowVisibility**

Fixes #60 
Fixes #61

### CODE REVIEW

**Review by Fredaly — APPROVED** [review]

File: Source/GitHubTools/Private/GitHubToolsHttpRequestManager.cpp [hunk 1]
```diff
@@ -126,7 +131,16 @@ TFuture< typename TRequest::ResponseType > FGitHubToolsHttpRequestManager::SendP
...
+            if constexpr ( TRequestTraits< TRequest >::IsGraphQL )
+            {
+                cursor = request_future_result.GetEndCursor();
+            }
+            else if constexpr ( TRequestTraits< TRequest >::IsRest )
+            {
+                page_index++;
+            }
+
+            // cursor = request_future_result.GetEndCursor();
```
Comment (Frickerson) [inline Source/GitHubTools/Private/GitHubToolsHttpRequestManager.cpp]: Remove or add comment

**Review by Frickerson — CHANGES_REQUESTED** [review]
